apiVersion: v1
kind: ReplicationController
metadata:
  name: harrisdemorepo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: harrisdemorepo
    spec:
      containers:
      - name: harrisdemorepo
        image: 475485431052.dkr.ecr.us-east-1.amazonaws.com/harrisdemorepo:latest
        ports:
        - containerPort: 1883
        imagePullPolicy: Always  
      imagePullSecrets:
        - name: ecrregistrypullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: harrisdemorepo
  labels:
    app: harrisdemorepo
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: harrisdemorepo
  selector:
    app: harrisdemorepo
