apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harrisdemorepo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: harrisdemorepo
    spec:
      containers:
      - name: harrisdemorepo
        image: 475485431052.dkr.ecr.us-east-1.amazonaws.com/harrisdemorepo:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: harrisdemorepo
  labels:
    app: harrisdemorepo
    tier: harrisdemorepo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: harrisdemorepo
