apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harrisdemorepo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SpringBootMavenExample
    spec:
      containers:
      - name: harrisdemorepo
        image: 475485431052.dkr.ecr.us-east-1.amazonaws.com/harrisdemorepo:latest
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: my-aws-crdentials
---
apiVersion: v1
kind: Service
metadata:
  name: harrisdemorepo
  labels:
    app: SpringBootMavenExample
    tier: harrisdemorepo
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: SpringBootMavenExample
